/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author ti.raoni
 */
public class ViewPrincipal extends javax.swing.JFrame {
    
    
    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() throws IOException {
        initComponents();
        setLocationRelativeTo(null);
         
        
        this.setIconImage(ImageIO.read(this.getClass().getResourceAsStream("/imagens/botoes/icon_cartao.png")));
        setTitle("SP Zaragoza v1.0");

    }
public void Login(String login) {
jLabel1.setText(login);
String admin = login;
boolean condicao = false;
if(admin.equals("admin")){
    condicao = true;
    } else {
    condicao = false;
}
jbUsuarios.setEnabled(condicao);
jbLojas.setEnabled(condicao);
jbFornecedores.setEnabled(condicao);
jbFormaPagamento.setEnabled(condicao);
jmLojas.setEnabled(condicao);
jmUsuarios.setEnabled(condicao);
jmForma.setEnabled(condicao);
jmFornecedores.setEnabled(condicao);

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbUsuarios = new javax.swing.JButton();
        jbLojas = new javax.swing.JButton();
        jbFornecedores = new javax.swing.JButton();
        jbFormaPagamento = new javax.swing.JButton();
        jbSP = new javax.swing.JButton();
        jdpPrincipal = new javax.swing.JDesktopPane();
        uJPanelImagem1 = new componentes.UJPanelImagem();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmUsuarios = new javax.swing.JMenuItem();
        jmLojas = new javax.swing.JMenuItem();
        jmFornecedores = new javax.swing.JMenuItem();
        jmForma = new javax.swing.JMenuItem();
        jmSP = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmSair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/icons8-usuário-verificado-masculino-64.png"))); // NOI18N
        jbUsuarios.setText("Usuários");
        jbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(jbUsuarios);

        jbLojas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/icons8-loja-64.png"))); // NOI18N
        jbLojas.setText("Lojas");
        jbLojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLojasActionPerformed(evt);
            }
        });
        jPanel2.add(jbLojas);

        jbFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/icons8-fornecedor-64.png"))); // NOI18N
        jbFornecedores.setText("Fornecedores");
        jbFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFornecedoresActionPerformed(evt);
            }
        });
        jPanel2.add(jbFornecedores);

        jbFormaPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/icons8-dinheiro-64.png"))); // NOI18N
        jbFormaPagamento.setText("Formas de Pagamento");
        jbFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFormaPagamentoActionPerformed(evt);
            }
        });
        jPanel2.add(jbFormaPagamento);

        jbSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/icons8-talão-de-cheques.-64.png"))); // NOI18N
        jbSP.setText("Solicitação de Pagamento");
        jbSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSPActionPerformed(evt);
            }
        });
        jPanel2.add(jbSP);

        uJPanelImagem1.setImagem(new java.io.File("C:\\TEMP\\spzaragoza\\imagens\\fundo_principal.jpg"));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Quem está logado");

        jLabel2.setText("Usuário:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)))
        );

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addContainerGap(547, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jdpPrincipal.setLayer(uJPanelImagem1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
            .addComponent(jdpPrincipal)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdpPrincipal))
        );

        jMenu2.setText("Arquivos");

        jmUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jmUsuarios.setText("Usuários");
        jmUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(jmUsuarios);

        jmLojas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmLojas.setText("Lojas");
        jmLojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLojasActionPerformed(evt);
            }
        });
        jMenu2.add(jmLojas);

        jmFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmFornecedores.setText("Fornecedores");
        jmFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFornecedoresActionPerformed(evt);
            }
        });
        jMenu2.add(jmFornecedores);

        jmForma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmForma.setText("Formas Pagamento");
        jmForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormaActionPerformed(evt);
            }
        });
        jMenu2.add(jmForma);

        jmSP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmSP.setText("Solicitação de Pagamento");
        jmSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSPActionPerformed(evt);
            }
        });
        jMenu2.add(jmSP);
        jMenu2.add(jSeparator1);

        jmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jmSair.setText("Sair");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jMenu2.add(jmSair);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmLojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLojasActionPerformed
       ViewFormaPagamento viewFormaPagamento = new ViewFormaPagamento();
       jdpPrincipal.add(viewFormaPagamento);
       viewFormaPagamento.setVisible(true);
    }//GEN-LAST:event_jmLojasActionPerformed

    private void jbFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFornecedoresActionPerformed
       ViewForn viewForn = new ViewForn();
       jdpPrincipal.add(viewForn);
       viewForn.setVisible(true);
    }//GEN-LAST:event_jbFornecedoresActionPerformed

    private void jbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuariosActionPerformed
       ViewUser viewUser = new ViewUser();
       jdpPrincipal.add(viewUser);
       viewUser.setVisible(true);
    }//GEN-LAST:event_jbUsuariosActionPerformed

    private void jbFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFormaPagamentoActionPerformed
       ViewFormaPagamento viewFormaPagamento = new ViewFormaPagamento();
       jdpPrincipal.add(viewFormaPagamento);
       viewFormaPagamento.setVisible(true);
    }//GEN-LAST:event_jbFormaPagamentoActionPerformed

    private void jbLojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLojasActionPerformed
        ViewLoja viewLoja = new ViewLoja();
        jdpPrincipal.add(viewLoja);
        viewLoja.setVisible(true);
    }//GEN-LAST:event_jbLojasActionPerformed

    private void jmUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuariosActionPerformed
       ViewUser viewUser = new ViewUser();
       jdpPrincipal.add(viewUser);
       viewUser.setVisible(true);
    }//GEN-LAST:event_jmUsuariosActionPerformed

    private void jmFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFornecedoresActionPerformed
       ViewForn viewForn = new ViewForn();
       jdpPrincipal.add(viewForn);
       viewForn.setVisible(true);
    }//GEN-LAST:event_jmFornecedoresActionPerformed

    private void jmFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormaActionPerformed
       ViewFormaPagamento viewFormaPagamento = new ViewFormaPagamento();
       jdpPrincipal.add(viewFormaPagamento);
       viewFormaPagamento.setVisible(true);
    }//GEN-LAST:event_jmFormaActionPerformed

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmSairActionPerformed

    private void jmSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSPActionPerformed
       ViewSP viewSP = null;
        try {
            viewSP = new ViewSP();
        } catch (SQLException ex) {
            Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       jdpPrincipal.add(viewSP);
       viewSP.setVisible(true);
    }//GEN-LAST:event_jmSPActionPerformed

    private void jbSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSPActionPerformed
       ViewSP viewSP = null;
        try {
            viewSP = new ViewSP();
        } catch (SQLException ex) {
            Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       jdpPrincipal.add(viewSP);
       viewSP.setVisible(true);
    }//GEN-LAST:event_jbSPActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ViewSobre viewSobre = new ViewSobre();
       jdpPrincipal.add(viewSobre);
       viewSobre.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void habilitarDesabilitarCampos (boolean condicao) throws IOException{
        jbUsuarios.setEnabled(condicao);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewPrincipal().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jbFormaPagamento;
    private javax.swing.JButton jbFornecedores;
    private javax.swing.JButton jbLojas;
    private javax.swing.JButton jbSP;
    private javax.swing.JButton jbUsuarios;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenuItem jmForma;
    private javax.swing.JMenuItem jmFornecedores;
    private javax.swing.JMenuItem jmLojas;
    private javax.swing.JMenuItem jmSP;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JMenuItem jmUsuarios;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables
}
